language: cpp

matrix:
    include:
        - os: linux
          dist: xenial
          compiler: clang
          before_install: CC=clang CXX=clang++

        - os: linux
          dist: xenial
          compiler: gcc
          before_install: CC=gcc-7 CXX=g++-7 UPDATE_WEBSITE=true

        - os: linux
          dist: bionic
          compiler: clang
          before_install: CC=clang CXX=clang++

        - os: linux
          dist: bionic
          compiler: gcc

        - os: osx
          compiler: clang

        - os: windows
          before_install: EXTRA_CMAKE_FLAGS=(-G "Visual Studio 15 2017 Win64" -Thost=x64)

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libstdc++-7-dev

env:
    global:
        - secure: "B1EM2bHUOTeDkMSP4Yl2MBfzsDFpoDy/GGIfWUFhya5KUI1L6vwXPAfWi6jP8w0UGBZAx9x5XFJXKMGKs4Ark4YOlhdtMmwKjflVOFLoIiqjKshr/791XiA77axL3L5dO90noeOFzXL7NBOGry8zF1TjELuNk2JWJZpqU00pB9fnq8ruy6H3VQ+9jZ/eAnB9OVzCB7tQXj3P3bNoUbgz3ZoEKkEi7n9rHug9erXcbbogDKP0PQ9s6mlCmD1jq3gx1oZDeflLCdXJ3bFE7krG69Vi745OnaDhMpDcJm0qV9EAZWD41cX1qd1VCfwnUwCt7w5CP2P+uyotmQnUc0d572HzU9suGw/YINmEXLsX1Yqumm7d9gto5kuQE37D6GAo8duGEeFZVRv4uTX+AlBaL6nhRKNnQqhgKjKHpsPHzU/mBO3SsfL2wLMvUFGdw7lum/RRemritx7YUdXyUVwZV5fiFLNg2go0WMZd9UkX+WnM1isBMpxCL492wKe/8uECpfnamed1ECnHAYUGVT25tEEky4Frh0HD37CCmZ3f6YmZhEmnvrZGdqmwkf8VO7MXTS/u8HqWw2eS6/SjcpAwgs5RCH0E/dD6LuepvPmy2igBn4EBgKTjyAUCHt7M9T+PpsiOZ/+VwK29A+RLlk5SxGDjSVQHYwVJ7t0LXObMHFs="
        - LLVM_VERSION=9.0.0

install:
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
          export LLVM_TARBALL_NAME=clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-$(lsb_release -sr);
          wget --no-verbose http://releases.llvm.org/$LLVM_VERSION/$LLVM_TARBALL_NAME.tar.xz;
          tar -xf $LLVM_TARBALL_NAME.tar.xz;
          export LLVMDIR="$PWD/$LLVM_TARBALL_NAME";
          pip install --user lit;
      fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
          export LLVM_TARBALL_NAME=clang+llvm-$LLVM_VERSION-x86_64-darwin-apple;
          wget --no-verbose http://releases.llvm.org/$LLVM_VERSION/$LLVM_TARBALL_NAME.tar.xz;
          tar -xf $LLVM_TARBALL_NAME.tar.xz;
          export LLVMDIR="$PWD/$LLVM_TARBALL_NAME";
          pip2 install lit pyyaml;
      fi
    - if [ $TRAVIS_OS_NAME == "windows" ]; then
          curl -L "https://github.com/vovkos/llvm-package-windows/releases/download/llvm-master/llvm-$LLVM_VERSION-windows-amd64-msvc15-msvcrt.7z" --output llvm.7z && 7z x llvm.7z;
          curl -L "https://github.com/vovkos/llvm-package-windows/releases/download/clang-master/clang-$LLVM_VERSION-windows-amd64-msvc15-msvcrt.7z" --output clang.7z && 7z x clang.7z;
          export LLVMDIR="$PWD/llvm-$LLVM_VERSION-windows-amd64-msvc15-msvcrt";
          export CLANGDIR="$PWD/clang-$LLVM_VERSION-windows-amd64-msvc15-msvcrt";
          choco install python2;
          export PATH="/c/Python27:/c/Python27/Scripts:$PATH";
          pip install lit;
      fi
    - export PATH="$LLVMDIR/bin:$CLANGDIR/bin:$PATH"

script:
    - set -e
    - printenv
    - cmake --version
    - export CMAKE_BUILD_PARALLEL_LEVEL=""
    - cmake .
      -DCMAKE_PREFIX_PATH="$LLVMDIR;$CLANGDIR"
      -DCMAKE_BUILD_TYPE=Debug
      "${EXTRA_CMAKE_FLAGS[@]}"
    - cmake --build .
    - cmake --build . --target check
    - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_COMPILER == "clang" ]; then
          cmake --build . --target lint;
      fi

after_success:
    - if [ $UPDATE_WEBSITE == "true" ]; then
          wget --no-verbose https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb;
          sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb;
          scripts/ci-update-website.sh;
      fi
